### ISSUE TITLE
Channels not sync?

### ISSUE THREAD

**Issue by NeoLegends** [schets/multiqueue#29]
Seems like the channel primitives aren't `Sync`, is this desired?

**Comment by fmckeogh** [comment]
I think I need this as well to use a queue with `tokio`, unless I'm misunderstanding something.

**Comment by schets** [comment]
I haven't looked at this code in a while, but as designed now the Sender/Receiver structs aren't sync since they maintain local state which is only occasionally refreshed to avoid cache problems on shared variables.

One could add sync version of these which don't have this restriction however, but I don't have much time anymore for this project.
